set nocompatible
set t_Co=256
set shell=bash

call plug#begin()

	Plug 'vim-airline/vim-airline'
	Plug 'vim-airline/vim-airline-themes'

	Plug 'scrooloose/syntastic'

	Plug 'airblade/vim-gitgutter'

call plug#end()

set noshowmode
set laststatus=2

set showcmd         " Show (partial) command in status line.

set number          " Show line numbers.

set showmatch       " When a bracket is inserted, briefly jump to the matching
					" one. The jump is only done if the match can be seen on the
					" screen. The time to show the match can be set with
					" 'matchtime'.

set hlsearch		" When there is a previous search pattern, highlight all
					" its matches.

set incsearch		" While typing a search command, show immediately where the
					" so far typed pattern matches.

set ignorecase		" Ignore case in search patterns.

set smartcase		" Override the 'ignorecase' option if the search pattern
					" contains upper case characters.

set backspace=2		" Influences the working of <BS>, <Del>, CTRL-W
					" and CTRL-U in Insert mode. This is a list of items,
					" separated by commas. Each item allows a way to backspace
					" over something.

set autoindent		" Copy indent from current line when starting a new line
					" (typing <CR> in Insert mode or when using the "o" or "O"
					" command).

set textwidth=79	" Maximum width of text that is being inserted. A longer
					" line will be broken after white space to get this width.

set formatoptions=c,q,r,t	" This is a sequence of letters which describes how
							" automatic formatting is to be done.
							"
							" letter    meaning when present in 'formatoptions'
							" ------    ---------------------------------------
							" c         Auto-wrap comments using textwidth, inserting
							"           the current comment leader automatically.
							" q         Allow formatting of comments with "gq".
							" r         Automatically insert the current comment leader
							"           after hitting <Enter> in Insert mode.
							" t         Auto-wrap text using textwidth (does not apply
							"           to comments)

set ruler			" Show the line and column number of the cursor position,
					" separated by a comma.

set background=dark " When set to "dark", Vim will try to use colors that look
					" good on a dark background. When set to "light", Vim will
					" try to use colors that look good on a light background.
					" Any other value is illegal.

set mouse=a			" Enable the use of the mouse.

set scrolloff=10	" always keep 10 lines above and below cursor

set guifont=Cousine\ for\ Powerline

set shiftwidth=4
set tabstop=4

filetype plugin indent on
syntax on

set updatetime=250

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 1

let g:airline_theme='wombat'
let g:airline_powerline_fonts = 1

"colorscheme molokai

set list
set listchars=tab:>.
