# Path to your oh-my-zsh installation.
export ZSH=/usr/share/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="bira"

DISABLE_AUTO_UPDATE="true"

plugins=(thefuck chucknorris colored-man colorize nyan)

# User configuration

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/bin/core_perl:/usr/bin/vendor_perl"

source $ZSH/oh-my-zsh.sh

alias col='colorize_via_pygmentize'
alias cpu='watch grep \"cpu MHz\" /proc/cpuinfo'
alias actualizar='pacaur -Syu'
alias dpi='sudo sh ~/.dpi.sh'
alias yt-aria='sh ~/.yt.sh'

alias logcat='
	while true; do
		adb logcat;
	done
		'
alias pop2='
	cd;
	sh .pop.sh&;
	sleep 30;
	audacious POP/*
		'
alias pop='
	while true; do
		mpv2 rtmp://popradio.stweb.tv:1935/popradio/live --cache-initial=1100 --cache-pause --cache-secs=30;
	done
		'
alias yt='
	url2=""
	url=""

	url2=$(xclip -o);

	if [[ $url2 ]]; then
		url=$url2
		url2=""
		youtube-dl -e --get-description --get-format $url && mpv "--ytdl" "--ytdl-format=bestvideo[height<=?1080]+bestaudio/best" ${url}
	fi
		'
alias yt720='
	url2=""
	url=""

	url2=$(xclip -o);

	if [[ $url2 ]]; then
		url=$url2
		url2=""
		youtube-dl -e --get-description --get-format $url && mpv "--ytdl" "--ytdl-format=bestvideo[height<=?720]+bestaudio/best" ${url}
	fi
		'
alias aria='
	echo `xclip -o`;
	aria2c --allow-overwrite=true -c --file-allocation=none --log-level=error -m2 -x8 --max-file-not-found=5 -k5M --no-conf -Rtrue --summary-interval=60 -t5 `xclip -o`
		'
alias bleach='
	cd;
	killall spotify;
	mv .cache/spotify spotify;
	sudo bleachbit;
	bleachbit;
	mv spotify .cache/spotify
		'
