# Path to your oh-my-zsh installation.
export ZSH=/usr/share/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="bira"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#plugins=(thefuck git chucknorris colored-man colorize command-not-found)
plugins=(thefuck chucknorris colored-man colorize nyan)

# User configuration

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/bin/core_perl:/usr/bin/vendor_perl"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#alias pop='cd POP; while true; do rtmpdump -i rtmp://popradio.stweb.tv:1935/popradio/live -o "`date +%Y_%m_%d__%H_%M`.acc" -v; done'
#alias mpsyt='cd && ./mps-youtube/mpsyt'
#alias steam='export LD_PRELOAD="/usr/lib/libasound.so.2:/usr/lib64/libasound.so.2"; steam'
#alias wwz='xrandr --output HDMI-0 --mode 1600x900'
#alias zzw='xrandr --output HDMI-0 --mode 1920x1080'
#alias midori='GTK_CSD=1 midori'
#alias pop2='cd; sh Beto.sh&; sleep 30; mpv POP --no-video'
#alias alerta='zenity --error --text "Esto es un error T_T" &; for i in {1..3}; do sleep 3; mpv --really-quiet /usr/share/sounds/mate/default/alerts/bark.ogg; done'

alias col='colorize_via_pygmentize'
alias yaourt='pacaur'
alias logcat='while true; do adb logcat; done'
alias cpu='watch grep \"cpu MHz\" /proc/cpuinfo'
alias pop2='cd; sh .pop.sh&; sleep 30; audacious POP/*'
alias pop='while true; do mpv2 rtmp://popradio.stweb.tv:1935/popradio/live --cache-initial=1100 --cache-pause --cache-secs=30; done'
alias yt='url=$(xclip -o); youtube-dl -e --get-description --get-format $url && mpv "--ytdl" "--ytdl-format=bestvideo[height<=?1080]+bestaudio/best" ${url}'
alias yt720='url=$(xclip -o); youtube-dl -e --get-description --get-format ${url} && mpv "--ytdl" "--ytdl-format=bestvideo[height<=?720]+bestaudio/best" ${url}'
alias aria='echo `xclip -o`; aria2c --allow-overwrite=true -c --file-allocation=none --log-level=error -m2 -x8 --max-file-not-found=5 -k5M --no-conf -Rtrue --summary-interval=60 -t5 `xclip -o`'
alias actualizar='pacaur -Syu'
alias dpi='cd && sudo sh .dpi.sh'
alias bleach='killall spotify; mv .cache/spotify spotify && sudo bleachbit; bleachbit; mv spotify .cache/spotify'
